apiVersion: v1
kind: Service
metadata:
  name: agar-service
spec:
  type: NodePort
  selector:
    app: agar-clone
  ports:
    - port: 3000
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 3000
      nodePort: 30007